<template>
  <div>
    <v-row dense>
      <v-col class="d-flex" cols="12" sm="6">
        <v-autocomplete :items="department" label="Type" outlined></v-autocomplete>
      </v-col>
    </v-row>
    <v-row>
      <v-col class="text-center" cols="12" sm="12">
        <div class="ma-2">
          <v-btn depressed large color="deep-orange darken-1">Search</v-btn>
        </div>
      </v-col>
    </v-row>
  </div>
</template>

<script>
export default {
  data() {
    return {
      department: [
        "A/R",
        "AAS",
        "ACCT",
        "AE",
        "AFRS",
        "AIS",
        "AM",
        "ANTH",
        "ARAB",
        "ARMN",
        "ART",
        "ASTR",
        "ATHL",
        "BIOL",
        "BLAW",
        "BUS",
        "CADV",
        "CAS",
        "CCE",
        "CD",
        "CE",
        "CECS",
        "CHEM",
        "CHIN",
        "CHS",
        "CIT",
        "CJS",
        "CLAS",
        "CM",
        "COMP",
        "COMS",
        "CTVA",
        "DEAF",
        "ECE",
        "ECON",
        "EDUC",
        "EED",
        "ELPS",
        "ENGL",
        "EOH",
        "EPC",
        "FCS",
        "FIN",
        "FLIT",
        "FREN",
        "GBUS",
        "GEOG",
        "GEOL",
        "GWS",
        "HEBR",
        "HHD",
        "HIST",
        "HSCI",
        "HUM",
        "IS",
        "ITAL",
        "JAPN",
        "JOUR",
        "JS",
        "KIN",
        "KOR",
        "LING",
        "LRS",
        "MATH",
        "MCOM",
        "ME",
        "MGT",
        "MKT",
        "MPA",
        "MSE",
        "MUS",
        "NURS",
        "PERS",
        "PHIL",
        "PHSC",
        "PHYS",
        "POLS",
        "PSY",
        "PT",
        "QS",
        "RE",
        "RS",
        "RTM",
        "RUSS",
        "SBS",
        "SCI",
        "SCM",
        "SED",
        "SOC",
        "SOM",
        "SPAN",
        "SPED",
        "SUST",
        "SWRK",
        "TH",
        "UNIV",
        "URBS"
      ]
    };
  }
};
</script>
